server:
  port: 8080
spring:
  application:
    name:
      SaveMoney$lot
  config:
    import: optional:configserver:http://config-server:8888/
  cloud:
    config:
      label: main

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs


