CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY 
        (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_check CHECK 
        (name::text = ANY (ARRAY['ADMIN'::character varying, 'USER'::character varying]::text[])),
    CONSTRAINT roles_name_unique UNIQUE (name)
);

CREATE SEQUENCE IF NOT EXISTS users_seq START 1 INCREMENT 50;

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY 
        (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    balance NUMERIC(19, 2) NOT NULL DEFAULT 0,
    birthdate DATE,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.users_roles
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT users_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_user_id FOREIGN KEY (user_id)
        REFERENCES public.users (id) ON DELETE CASCADE,
    CONSTRAINT fk_users_roles_role_id FOREIGN KEY (role_id)
        REFERENCES public.roles (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_users_roles_role_id ON public.users_roles(role_id);

INSERT INTO public.roles (name)
VALUES ('ADMIN'), ('USER')
ON CONFLICT (name) DO NOTHING;

CREATE SEQUENCE IF NOT EXISTS goals_seq START 1 INCREMENT 50;

CREATE TABLE goals (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('goals_seq'::regclass),
    name VARCHAR(255) NOT NULL,
    target_amount NUMERIC(19, 2) NOT NULL,
    saved_amount NUMERIC(19, 2) NOT NULL DEFAULT 0,
    reason VARCHAR(255),
    deadline TIMESTAMP WITHOUT TIME ZONE,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_goals_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT goals_target_amount_check CHECK (target_amount >= 0)
);

CREATE SEQUENCE IF NOT EXISTS transactions_categories_seq START 1 INCREMENT 50;

CREATE TABLE transactions_categories (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('transactions_categories_seq'::regclass),
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_transactions_categories_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT transactions_categories_type_check CHECK (type IN ('EXPENSE', 'INCOME', 'INVESTMENT'))
);

CREATE SEQUENCE IF NOT EXISTS transactions_seq START 1 INCREMENT 50;

CREATE TABLE transactions (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('transactions_seq'::regclass),
    value NUMERIC(19, 2) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    category_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_transactions_category FOREIGN KEY (category_id) REFERENCES transactions_categories(id),
    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users(id)
);