name: Java CI with Docker Compose Postgres

on: push

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env-test file
        run: cp .env-test .env

      - name: Build images and start database
        run: docker compose --env-file .env-test up --build -d --wait db

      - name: Run tests inside the app container
        run: docker compose --env-file .env-test run --rm app ./gradlew test

      - name: Clean up services
        if: always()
        run: docker compose down -v --remove-orphans

